---
title: "Lab 4"
author: "Hailey Werth and Myles Cagle"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    toc_depth: 2
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, message = FALSE, progress = FALSE)
```

# Reading/Cleaning the Data
```{r}
pacman::p_load(tidyverse, magrittr, lubridate, hms, iptools, corrplot, caretEnsemble, DMwR, caret, pROC, glmnet, rpart, e1071)

##function to analyze test data
predResults_fun = function(modelsObject, testObject){
  allModelsClassPreds = lapply(modelsObject, predict, newdata = testObject, type="raw") %>% 
    data.frame()
  
  resultsSensSpec = lapply(allModelsClassPreds, confusionMatrix, testObject$CLASS_LABEL) %>% 
    lapply("[[", "byClass") %>% as.data.frame() %>% 
    dplyr::slice(c(1,2))
  row.names(resultsSensSpec) = c("Sensitivity","Specificity")
  
  resultsAcc = lapply(allModelsClassPreds, confusionMatrix, testObject$CLASS_LABEL) %>% 
    lapply("[[", "overall") %>% as.data.frame() %>% 
    dplyr::slice(c(1))
  row.names(resultsAcc) = "Accuracy"
  
  resultsAUC = lapply(modelsObject, predict, newdata = testObject, type="prob") %>% 
    lapply(function(x) x[,"Yes"]) %>% lapply(colAUC, testObject$CLASS_LABEL) %>% 
    data.frame(row.names = "AUC")
  
  resultsGmean = sqrt(resultsSensSpec["Sensitivity",] *resultsSensSpec["Specificity",]  )
  row.names(resultsGmean) = "Gmean"
  
  results = rbind(resultsAUC, resultsAcc, resultsSensSpec, resultsGmean) %>% data.frame()
  results
}

#add headers from text file
featuresDF = read.csv("featMat.csv", header = F)

colnames(featuresDF) = c('user id',
                         'doc id',
                         'inter-stroke time',
                         'stroke duration',
                         'start x',
                         'start y',
                         'stop x',
                         'stop y',
                         'direct end-to-end distance',
                         'mean resultant length',
                         'up/down/left/right flag',
                         'direction of end-to-end line',
                         'phone id',
                         '20% pairwise velocity',
                         '50% pairwise velocity',
                         '80% pairwise velocity',
                         '20% pairwise acc',
                         '50% pairwise acc',
                         '80% pairwise acc',
                         'median velocity at last 3 pts',
                         'largest deviation from end-to-end line',
                         '20% dev. from end-to-end line',
                         '50% dev. from end-to-end line',
                         '80% dev. from end-to-end line',
                         'average direction',
                         'length of trajectory',
                         'ratio end-to-end dist and length of trajectory',
                         'average velocity',
                         'median acceleration at first 5 points',
                         'mid-stroke pressure',
                         'mid-stroke area covered',
                         'mid-stroke finger orientation',
                         'change of finger orientation',
                         'phone orientation')

featuresDF %<>% mutate_if(is.integer, as.factor)
user2DF <- featuresDF
user2DF$`user id` <- if_else(featuresDF$`user id` == '2', 'user', "not")
user2DF$`user id` <- as.factor(user2DF$`user id`)

df <- user2DF

table(df$`doc ID`)

```

# Inter-week: Train on doc.id 1-3, test on doc.id 6
```{r}
train1 = data.frame()
test1 = data.frame()

train1 = filter(df, df$`doc id` == "1" | df$`doc id` == "2" | df$`doc id` == "3")
test1 = filter(df, df$`doc id` == "6")

trainNA = na.omit(train1)
trainNA %<>% select(-'change of finger orientation', -'phone id', -'doc id')

testNA = na.omit(test1)
testNA %<>% select(-'change of finger orientation', -'phone id', -'doc id')
```


# Inter-session: Train on doc.id 1-2, test on an untrained doc.id
```{r}
train2 = data.frame()
test2 = data.frame()

train2 = filter(df, df$`doc id` == "1" | df$`doc id` == "2")
test2 = filter(df, df$`doc id` == "3")

trainNA2 = na.omit(train2)
trainNA2 %<>% select(-'change of finger orientation', -'phone id', -'doc id')

testNA2 = na.omit(test2)
testNA2 %<>% select(-'change of finger orientation', -'phone id', -'doc id')

```


# Intra-session: Train and test on one session doc.id
```{r}
train3 = data.frame()
test3 = data.frame()

train3 = filter(df, df$`doc id` == "2")
test3 = filter(df, df$`doc id` == "2")

trainNA3 = na.omit(train3)
trainNA3 %<>% select(-'change of finger orientation', -'phone id', -'doc id')

testNA3 = na.omit(test3)
testNA3 %<>% select(-'change of finger orientation', -'phone id', -'doc id')

```

# Building Models
```{r}
fitControl = trainControl(method = "repeatedcv",
                          number = 5,
                          sampling = "down",
                          summaryFunction = twoClassSummary,
                          classProbs = T,
                          selectionFunction = "best",
                          savePredictions = T,
                          index = createResample(trainNA$`user id`, times = 5))

fitControl2 = trainControl(method = "repeatedcv",
                          number = 5,
                          sampling = "down",
                          summaryFunction = twoClassSummary,
                          classProbs = T,
                          selectionFunction = "best",
                          savePredictions = T,
                          index = createResample(trainNA2$`user id`, times = 5))

fitControl3 = trainControl(method = "repeatedcv",
                          number = 5,
                          sampling = "down",
                          summaryFunction = twoClassSummary,
                          classProbs = T,
                          selectionFunction = "best",
                          savePredictions = T,
                          index = createResample(trainNA3$`user id`, times = 5))

models = caretList(`user id` ~ ., data = trainNA, metric = "ROC",
                   tuneList = list(
                     svm = caretModelSpec(method = "svmRadial", family = "binomial"),
                     knn = caretModelSpec(method = "knn", tuneGrid = expand.grid(.k = seq(1,7,2)))
                   ),
                   trControl = fitControl,
                   preProcess = c("nzv", "center", "scale", "corr")
)

models2 = caretList(`user id` ~ ., data = trainNA2, metric = "ROC",
                   tuneList = list(
                     svm = caretModelSpec(method = "svmRadial", family = "binomial"),
                     knn = caretModelSpec(method = "knn", tuneGrid = expand.grid(.k = seq(1,7,2)))
                   ),
                   trControl = fitControl2,
                   preProcess = c("nzv", "center", "scale", "corr")
)

models3 = caretList(`user id` ~ ., data = trainNA3, metric = "ROC",
                   tuneList = list(
                     svm = caretModelSpec(method = "svmRadial", family = "binomial"),
                     knn = caretModelSpec(method = "knn",tuneGrid = expand.grid(.k = seq(1,7,2)))
                   ),
                   trControl = fitControl3,
                   preProcess = c("nzv", "center", "scale", "corr")
)

cvResults = resamples(models)
cvResults2 = resamples(models2)
cvResults3 = resamples(models3)
scales = list(x=list(relation="free"), y=list(relation="free"))

lapply(models, varImp)
lapply(models2, varImp)
lapply(models3, varImp)

bwplot(cvResults, scales = scales)
bwplot(cvResults2, scales = scales)
bwplot(cvResults3, scales = scales)

```

# Testing Models
```{r}
confMatrix = lapply(models, predict, newdata = testNA, type="raw") %>% 
  lapply(confusionMatrix, testNA$`user id`) %>% 
  lapply("[[", "table")

confMatrix

confMatrix2 = lapply(models, predict, newdata = testNA2, type="raw") %>% 
  lapply(confusionMatrix, testNA2$`user id`) %>% 
  lapply("[[", "table")

confMatrix2

confMatrix3 = lapply(models, predict, newdata = testNA3, type="raw") %>% 
  lapply(confusionMatrix, testNA3$`user id`) %>% 
  lapply("[[", "table")

confMatrix3

```


